### ISSUE TITLE
Use inverted cloud.gov logo

### ISSUE THREAD

**Issue by eddietejeda** [18F/cg-deploy-stratos#14]
https://gsa-tts.slack.com/archives/CNFHBCXDW/p1580768177049400?thread_ts=1580742375.043900&cid=CNFHBCXDW

**Comment by tammersaleh** [comment]
Work being done in https://github.com/18F/cg-deploy-stratos/pull/16

**Comment by tammersaleh** [comment]
new logo is now in dev/staging/prod
