### ISSUE TITLE
Upgrade to stratos 3.0.0

### ISSUE THREAD

**Issue by tammersaleh** [18F/cg-deploy-stratos#18]
~~Once the stratos team cuts a stable `3.0.0` release~~ Now that stratos 3.0.0 is released, we should upgrade.  This involves:

- [x] Pause the dev and prod pipeline
- [x] Change the `pipeline.yml` to add `filter_tag: stable` (should still use `branch: master`)
- [x] `fly set-pipeline`
- [x] Change the `manifest.yml` to use the [`#3` buildpack version](https://github.com/cloudfoundry/stratos/blob/master/manifest.yml#L7) (bonus points for somehow generating the manifest from the upstream example)
- [x] `git push`
- [x] Unpause dev and observe in staging
- [x] Unpause prod
- [x] Rebase
- [x] Merge https://github.com/18F/cg-deploy-stratos/pull/23
- [x] Update secrets to point to `master`
- [x] Upload secrets
- [x] Upload pipeline

## Security considerations

None.

**Comment by spgreenberg** [comment]
I think it would be advantageous to change the pipeline to use a github-release resource and only deploy cut releases. This gives us greater traceability and visibility into features and bug fixes in my experience.

**Comment by tammersaleh** [comment]
Blocked on https://github.com/18F/cg-provision/pull/708

**Comment by tammersaleh** [comment]
Concourse is being updated, so I'll wait for a green before calling this done.
